## PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.2+cu118


## Introduction to Tensors in PyTorch

### Creating Tensor

In [2]:
# scaler tensor
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
# This give us a python int
scaler.item()

7

In [5]:
# vector tensor
vector = torch.tensor([7,7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix Tensor

MATRIX = torch.tensor([[7,7],[7,10]])
MATRIX

tensor([[ 7,  7],
        [ 7, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 7, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR

TENSOR = torch.tensor([[[[1,2,3,4,5],
                         [1,2,3,5,6],
                         [4,5,6,7,3]]]])
TENSOR

tensor([[[[1, 2, 3, 4, 5],
          [1, 2, 3, 5, 6],
          [4, 5, 6, 7, 3]]]])

In [13]:
TENSOR.ndim

4

In [14]:
TENSOR.shape

torch.Size([1, 1, 3, 5])

## RANDOM TENSORS

#### WHY RANDOM TENSORS?
Random tensor are important because the way neural network learn is that they start with tensor full of random no and then adjust this tensor
```
start with random tensor -> look at data -> update random numbers -> look at data -> updata random numbers
```
Torch Random Tensor : https://pytorch.org/docs/stable/generated/torch.rand.html

In [15]:
# CREATING A RANDOM TENSOR  OF SIZE (3,4)

random_tensor = torch.rand((1,1,1,3,4),dtype = torch.float32)

In [16]:
random_tensor

tensor([[[[[0.4395, 0.0965, 0.5477, 0.1041],
           [0.5258, 0.5551, 0.9595, 0.2556],
           [0.5286, 0.2570, 0.6914, 0.5588]]]]])

In [17]:
random_tensor.ndim

5

In [18]:
random_tensor.shape

torch.Size([1, 1, 1, 3, 4])

In [19]:
# CREATING A RANDOM NUMBER WITH SIMILAR SHAPE TO AN IMAGE TENSOR

random_image_size_tensor = torch.rand((3,28,28)) # NO OF COLOR CHANNELS(RBG) , HEIGHT , WIDTH
random_image_size_tensor.ndim , random_image_size_tensor.shape

(3, torch.Size([3, 28, 28]))

### ZEROS AND ONES

In [20]:
#  CREATING A TENSOR OF ALL ZEROS
zeros = torch.zeros((2,4))

In [21]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# CREATING A TENSOR OF ALL ONE
ones = torch.ones((1,12))

In [23]:
ones

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

### creating a range of tensor and tensor like

In [25]:
# using torch arange
range = torch.arange(1,10,2)

In [26]:
range

tensor([1, 3, 5, 7, 9])

In [27]:
# create tensor like
new_zeros = torch.zeros_like(input = range)

In [28]:
new_zeros

tensor([0, 0, 0, 0, 0])

In [29]:
new_zeros # same shape like range tensor

tensor([0, 0, 0, 0, 0])

### DTYPE IN TORCH

**Note:** Tensor dtype has a three big error that can come accross while doing deep learning:
1. tensor not right datatype
2. tensor not right shape
3. tensor not on right device

In [30]:
 # Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device= "cpu", # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [32]:
# How to change the data type in pytorch
float_16 = float_32_tensor.type(torch.float16)

In [33]:
float_16 * float_32_tensor

tensor([ 9., 36., 81.])

### Manipulating Tensor (Tensor Operation)
1. Addition
2. Multiplication(Element wise)
3. Subtraction
4. Matrix Multiplication
5. Division

In [34]:
x = torch.tensor([1,2,3,4])
x = x + 10
x

tensor([11, 12, 13, 14])

In [35]:
x = torch.tensor([1,2,3,4])
x = x * 10
x

tensor([10, 20, 30, 40])

In [36]:
x = torch.tensor([1,2,3,4])
x = x - 10
x

tensor([-9, -8, -7, -6])

In [37]:
# Trying pytorch in built function
torch.mul(x,10)

tensor([-90, -80, -70, -60])

In [38]:
torch.add(x,100)

tensor([91, 92, 93, 94])

### Matrix Multiplication

Two main ways of performing multiplication in neural network and deep learning

1. Element wise Multiplication
2. Matrix Multiplication(Dot product)

There are two main rule that performing matrix multiplication needs to satisfy:
1. Inner dimension must match
2. `(2,3) @ (3,2) = (2,2)`

In [39]:
# Element wise Multiplication
print(f'{x} * {x}')
print(f'{x*x}')

tensor([-9, -8, -7, -6]) * tensor([-9, -8, -7, -6])
tensor([81, 64, 49, 36])


In [40]:
# Matrix Multiplication
print('Matrix multilication of x with x:',torch.matmul(x,x))

Matrix multilication of x with x: tensor(230)


#### One of the most common error is done when we are working with the shapes of the tensor

In [41]:
tensor_A = torch.tensor([[1,2,3]
                        ,[2,3,4]])

tensor_B = torch.tensor([[1,2,3],
                        [4,5,6],
                         [3,2,1]])

(tensor_A @ tensor_B).shape

torch.Size([2, 3])

In [42]:
tensor_A.T

tensor([[1, 2],
        [2, 3],
        [3, 4]])

In [43]:
# torch.mm() is same as of torch.matmul() and this is also same to x @ x

### Finding the min , max , sum , mean etc (tensor aggregates)

In [45]:
x = torch.arange(1,10)

In [46]:
torch.min(x) , x.min()

(tensor(1), tensor(1))

In [47]:
torch.max(x) , x.max()

(tensor(9), tensor(9))

In [48]:
torch.sum(x) , x.sum()

(tensor(45), tensor(45))

In [49]:
x.dtype

torch.int64

In [50]:
# torch.mean() -> requires the floating data type and if it is not the same datatype then it will produce error

In [51]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(5.), tensor(5.))

In [52]:
%%time
torch.mean(x.type(torch.float32))

CPU times: user 0 ns, sys: 804 µs, total: 804 µs
Wall time: 486 µs


tensor(5.)

In [53]:
%%time
x.type(torch.float32).mean()

CPU times: user 1.41 ms, sys: 0 ns, total: 1.41 ms
Wall time: 869 µs


tensor(5.)

## Finding position index of min and max element in the tensor

In [54]:
tensor_a = torch.arange(20,100,2)

In [55]:
tensor_a.argmin() # this is means that the min element ie 20 is at index 0

tensor(0)

In [56]:
tensor_a.argmax() # this is means that the max element ie 100 is at index 39

tensor(39)

## Reshaping , viewing , stacking  , squeezing and unsquesszing Tensor

1. Reshaping - reshapes the input tensor
2. view - return a view of an input tensor of certain shape but keep the same memory as the original tensor
3. stacking - combime multiple tensor on top of each other (vstack) or side by side (hstack)
4. squeeze - remove all `1` dimension from a tensor
5. unsqueeze - add a `1` dimension to a target tensor
6. Permute - return a view of input with dimension swapped in a certain way

In [57]:
x = torch.arange(1,10)

In [58]:
x , x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [59]:
# Reshaping - extra dimension
x_reshaped = x.reshape(3,3)

In [60]:
x_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [61]:
# Changing the view
x_view = x.view(3,3)
x , x_view # because view of a tensor shares the same memory -> x_view share the same memory as of x

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

In [62]:
# change in x_view will reuslt in change in x
x_view[:,2] = 100

In [63]:
x , x_view

(tensor([  1,   2, 100,   4,   5, 100,   7,   8, 100]),
 tensor([[  1,   2, 100],
         [  4,   5, 100],
         [  7,   8, 100]]))

In [64]:
# Stacking tensor on top of each other
x_stack = torch.stack([x_view , x_view])

In [65]:
x_stack

tensor([[[  1,   2, 100],
         [  4,   5, 100],
         [  7,   8, 100]],

        [[  1,   2, 100],
         [  4,   5, 100],
         [  7,   8, 100]]])

In [66]:
x_stack.shape , x_stack.ndim

(torch.Size([2, 3, 3]), 3)

In [67]:
y = torch.tensor([1,2,3,4,5,6])

In [68]:
torch.stack([y,y,y])

tensor([[1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6]])

In [69]:
torch.stack([y,y,y],dim = 1)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6]])

In [70]:
# torch.squeeze() -> remove all the single dimension from target tensor

In [71]:
y = torch.tensor([[1,2,3,4]])

In [72]:
y.shape , y.ndim

(torch.Size([1, 4]), 2)

In [73]:
y_squeezed = torch.squeeze(y)

In [74]:
y_squeezed.shape , y_squeezed.ndim

(torch.Size([4]), 1)

In [75]:
# torch.unsqueeze() -> add  a single dimension to a target tensor at the specific dim

In [76]:
y_squeezed , y_squeezed.shape, y_squeezed.ndim

(tensor([1, 2, 3, 4]), torch.Size([4]), 1)

In [77]:
y_unsqueezed = y_squeezed.unsqueeze(dim = 0)

In [78]:
y_unsqueezed, y_unsqueezed.shape , y_unsqueezed.ndim

(tensor([[1, 2, 3, 4]]), torch.Size([1, 4]), 2)

In [79]:
# torch.permutate - rearrange the dimension of target tensor in a specific order

x_tensor = torch.rand((2,3),dtype = torch.half)

In [80]:
x_tensor.shape

torch.Size([2, 3])

In [81]:
x_permutate = x_tensor.permute(1,0) # 1->0 and 0->1

In [82]:
x_permutate , x_tensor

(tensor([[0.8647, 0.1528],
         [0.3320, 0.1533],
         [0.4053, 0.3413]], dtype=torch.float16),
 tensor([[0.8647, 0.3320, 0.4053],
         [0.1528, 0.1533, 0.3413]], dtype=torch.float16))

### Selecting data from tensor (Indexing)
Indexing in pytorch is similar to numpy indexing

In [84]:
x = torch.rand((1,2,3),dtype = torch.float32)

In [85]:
x.shape

torch.Size([1, 2, 3])

In [86]:
x[0] # -> this is the first row of dim 1

tensor([[0.2874, 0.6292, 0.3600],
        [0.3795, 0.8271, 0.7286]])

In [87]:
x[0,0] # -> this is the inner dimension of the first row

tensor([0.2874, 0.6292, 0.3600])

In [88]:
x[0,0,0] # -> most inner bracket

tensor(0.2874)

In [89]:
x[0,1,1] # x[1,1,1] -> this will produce error because we have [1,2,3] as a dimension of x and we can't go beyond that

tensor(0.8271)

In [90]:
x[:,:,1]

tensor([[0.6292, 0.8271]])

## Pytorch and Numpy

Numpy is the scientific lib that has the capabalities of appling some changes to array like structure and pytorch has the functionalities to intract with numpy.

* using `torch.from_numpy(ndarray)` -> convert numpy ndarray to tensor
* using `torch.tensor.numpy()` -> convert tensor to numpy

In [91]:
import numpy as np
import torch

In [92]:
array = np.arange(1.0,10.0)
tensor = torch.from_numpy(array)
tensor

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

In [93]:
array = array + 1

In [94]:
array , tensor

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [95]:
t = torch.ones((2,4))

In [96]:
t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [97]:
array_1 = torch.Tensor.numpy(t)

In [98]:
array_1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

### Changing the `tensor` what happen to `numpy` array

* Nothing happen because tensor and numpy array shares the different memory

In [99]:
t = t + 1
t,array_1

(tensor([[2., 2., 2., 2.],
         [2., 2., 2., 2.]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32))

### `Topic of reproducibility` 

* Trying to make of random out of random
* In short how a neural network learns:
* `start with random numbers -> tensor operation -> update random numbers to try and make them better representation of that data -> again and again this steps are followed for predefined epochs`
* To reduce the randomness in neural network and pytorch comes with the concept of a **random seeds**
* **random seeds** -> flavours the randomness
* https://en.wikipedia.org/wiki/Random_seed

In [100]:
import torch

# Creating two random no
tensor_A = torch.rand(3,4)
tensor_B = torch.rand(3,4)

print(tensor_A == tensor_B)
print(tensor_A)
print(tensor_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
tensor([[0.7147, 0.7850, 0.2895, 0.0686],
        [0.1085, 0.5367, 0.9154, 0.5952],
        [0.2828, 0.6679, 0.5441, 0.9473]])
tensor([[0.7298, 0.8096, 0.2397, 0.7879],
        [0.1759, 0.0718, 0.2450, 0.7626],
        [0.9490, 0.5251, 0.1430, 0.1707]])


In [101]:
# Let's make some random but reproducible tensor
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(3,3)
#torch.manual_seed(RANDOM_SEED) # -> make sure that every time you have to use torch.manual_seed() for each block of below code 
tensor_B = torch.rand(3,3)

print(tensor_A == tensor_B)
print(tensor_A)
print(tensor_B)

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])


### Running tensor and pytorch object on GPU (and making accelerated computing using cuda + nvidia Harware)
### Getting the GPU

1. Easiest way is to use Google colab
2. Use your own GPU
3. Use cloud Computing Azure , Aws etc 

### Check whether GPU is available or not

* If the device is capable of using GPU using cuda then it is important to set up agnostic device setup

In [104]:
import torch
torch.cuda.is_available()

True

In [105]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [106]:
# Count the deivce
torch.cuda.device_count()

1

### Putting tensor and model on GPU if available 

* This will lead to a faster computations

In [107]:
tensor = torch.tensor([1,2,3])
tensor , tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [108]:
# Moving tensor on GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu , tensor_on_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [109]:
# Moving tensor back to cpu
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3])